name: StueyB
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24321
title: Corners and Curves
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c6c6c6'
    - '#a3a3a3'
    - '#ededed'
    - '#4e4e4e'
  brandStrength: 0.22707421495579183
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
